name: "Changelog and release generator"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  changelog_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@1.1.0
        with:
          version: ${{ env.RELEASE_VERSION }}
      - name: Initialize mandatory git config
        run: |
          git config user.name "R2D2"
          git config user.email noreply@github.com
      - name: Bump version in package.json
        run: yarn version --new-version ${{ env.RELEASE_VERSION }} --no-git-tag-version
      - name: Commit changelog and manifest files
        id: make-commit
        run: |
          git add CHANGELOG.md package.json
          git commit --message "new release ${{ env.RELEASE_VERSION }}"

          echo "::set-output name=commit::$(git rev-parse HEAD)"
      - name: Push new branch
        run: git push origin HEAD:main
